"""added pokemon table

Revision ID: ef3645d2124c
Revises: ffdc0a98111c
Create Date: 2023-03-29 12:42:51.077836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3645d2124c'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('evolutions', sa.String(), nullable=True),
    sa.Column('evo_level', sa.Integer(), nullable=True),
    sa.Column('moves', sa.String(), nullable=False),
    sa.Column('types', sa.String(), nullable=False),
    sa.Column('locations', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###